Test sudo version automatically

diff --git a/cranky b/cranky
--- a/cranky
+++ b/cranky
@@ -18,6 +18,51 @@ function log_info {
 
 Theory=("sft.cern.ch" "grid.cern.ch" "cernvm-prod.cern.ch" "alice.cern.ch")
 
+function is_uint {
+    # test if $1 is unsigned integer
+    case $1 in
+      '' | *[!0-9]*)
+        return 1
+        ;;
+    esac
+}
+
+
+function version_is_lower {
+    # expects the classical version pattern major.minor.release[.subrelease...]
+    # with major, minor, release being unsigned integers
+    # $1: version to be tested
+    # $2: pattern to be tested against
+    # $3: controls the #sections to be compared (from left to right)
+    # returns
+    # 0: in case of $1 is lower than $2
+    # 1: in case of $1 is equal or higher than $2
+    # 2: in case of an error
+    
+    is_uint "$3" || return 2
+    sections=$3
+    
+    IFS=. read -a ver_arr <<<"$1" || return 2
+    IFS=. read -a pat_arr <<<"$2" || return 2
+    
+    (( ${#ver_arr[@]} < $sections )) || (( ${#pat_arr[@]} < $sections )) && return 2
+
+    for (( i=0; i<$sections; i++ )); do
+        is_uint "${ver_arr[$i]}" || return 2
+        is_uint "${pat_arr[$i]}" || return 2
+    done
+    
+    for (( i=0; i<$sections; i++ )); do
+        (( ${ver_arr[$i]} < ${pat_arr[$i]} )) && return 0
+        (( ${ver_arr[$i]} > ${pat_arr[$i]} )) && return 1
+    done
+    
+    ((sections--))
+    (( ${ver_arr[$sections]} == ${pat_arr[$sections]} )) && return 1
+    return 2
+}
+
+
 function get_boinc_info {
     if [ ! -f init_data.xml ] ; then
 	log_error "'init_data.xml' is missing."
@@ -453,18 +498,25 @@ function check_local_requirements {
         (( ret_clr < 2 )) && ret_clr=2
     fi
 
-    log_info "Found $(head -n1 <(sudo -V))."
-
-    sudoers_file="/etc/sudoers.d/50-lhcathome_boinc_theory_native"
-    if ! grep -qm1 "$sudoers_file" <(sudo -nl) 2>/dev/null; then
-        log_info "Can't find or read '$sudoers_file'."
+    sudo_min_version="1.9.10"
+    sudo_version="$(grep -Piom1 'version[^0-9]+\K.*' <(sudo -V 2>/dev/null) 2>/dev/null)"
+    log_info "Found Sudo-Version $sudo_version."
+    
+    if version_is_lower "${sudo_version%%[^0-9\.]*}" "$sudo_min_version" 3; then
+        log_info "To run this task in new mode"
+        log_info "Sudo-Version must be at least $sudo_min_version."
         (( ret_clr < 1 )) && ret_clr=1
     else
-        if ! sudo -n /usr/bin/cat $sudoers_file >/dev/null 2>&1; then
-            log_info "Found '$sudoers_file'"
-            log_info "but sudo may not be able to interpret regular expressions."
-            log_info "Upgrade sudo to version 1.9.10 or higher."
+        sudoers_file="/etc/sudoers.d/50-lhcathome_boinc_theory_native"
+        if ! grep -qm1 "$sudoers_file" <(sudo -nl 2>/dev/null) 2>/dev/null; then
+            log_info "Can't find or read '$sudoers_file'."
             (( ret_clr < 1 )) && ret_clr=1
+        else
+            if ! sudo -n /usr/bin/cat $sudoers_file >/dev/null 2>&1; then
+                log_info "Found '$sudoers_file'"
+                log_info "but sudo may not be able to interpret it."
+                (( ret_clr < 1 )) && ret_clr=1
+            fi
         fi
     fi
 
